name: Sync to HuggingFace Space

on:
  push:
    branches:
      - main

jobs:
  sync-to-hf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Remove binary files before HF push
        run: |
          find . -name "*.zip" -exec git rm --cached --ignore-unmatch {} \;

      - name: Push to HuggingFace Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "jhawardev11@gmail.com"
          git config --global user.name "DEVJHAWAR11"
          git remote add hf https://DEVJHAWAR11:${HF_TOKEN}@huggingface.co/spaces/devjhawar/policylens-rag-api
          git push hf main --force
